---
- name: demotest
  hosts: all
  become: true

  tasks:

  - name: install package phyton
    ansible.builtin.dnf:
      name: phyton3-dnf
      state: latest
      
  - name: install nginx
    yum:
      name: nginx
      state: latest

  - name: start nginx
    service:
      name: nginx
      state: started
