---
- name: Tambah User
  hosts: all
  become: yes
  tasks:
    - name: Buat user baru
      ansible.builtin.user:
        name: johndoe
        shell: /bin/bash
        state: present

    - name: Change user password in /etc/shadow
      ansible.builtin.user:
        name: "johndoe"
        password: "P@ssw0rd"
        update_password: always
      no_log: true
