---
- name: Tambah User
  hosts: all
  become: true
  tasks:
    - name: Buat user baru
      ansible.builtin.user:
        name: johndoe
        shell: /bin/bash
        state: present

    - name: Change user password in /etc/shadow
      ansible.builtin.user:
        name: "johndoe"
        password: "{{ 'P@ssw0rd' | password_hash('sha512') }}"
        update_password: always
      no_log: true
