- name: Add the user 'johnd' with a specific uid and a primary group of 'admin'
  hosts: all

  tasks:
  - name: Create user John Doe
    ansible.builtin.user:
      name: johnd
      comment: John Doe
      uid: 1040
